name: BuildBattle
main: Crack\BB
api: [1.0.0, 2.0.0]
version: 1.3.0
author: Crack Pixel And Pyxel Ruby

commands:
    bb:
        usage: /bb <make>
        description: CreateGame
permissions:
    bb.op:
        default: op
  